### ISSUE TITLE
Import order

### ISSUE THREAD

**Issue by rvolosatovs** [ckaznocha/protoc-gen-lint#10]
Would be great if the tool could also check if imports are ordered in a consistent way. (Maybe simply alphabetical?)

**Comment by ckaznocha** [comment]
Good idea! I’ll look into it

**Comment by allenhartwig** [comment]
Is there a functional motivation behind this rule? If purely an aesthetic/readability motive, is there a way to disable the rule from the command line? This is now breaking our tests, and we would rather not refactor our proto files to adhere to this rule at this time.

**Comment by ckaznocha** [comment]
Sorry about that @allenhartwig, I'll get the fix out soon
