### ISSUE TITLE
Status Code 2 return

### ISSUE THREAD

**Issue by johnco3** [ckaznocha/protoc-gen-lint#2]
I tried using your lint on my Proto3 file however it failed.   Not sure what the issue could be

C:\main\dlmu\cadaemon-0339.1\include\cagrpc>protoc --lint_out=. CAService.proto
--lint_out: protoc-gen-lint: Plugin failed with status code 2.

I am using the latest x64 protoc using the master branch.  My protoc files are used for gRPC. It would be really useful if there was some descriptive text indicating what Status code 2 means

**Comment by ckaznocha** [comment]
Are you able to post your .proto file?

**Comment by johnco3** [comment]
I think there is a problem with the binary, firstly it has no extension for
the win32 executable.  After renaming it I received the following popup -
also not sure but I think I may be forced to specify the '-I .' in order
for the default usage to find the proto files

I'll try again as soon as you have a newer version

John

[image: Inline image 1]

**Comment by ckaznocha** [comment]
Something went wrong with the travis cross compilation. I've just manually regenerated the binaries. Let me know if you still have an issue getting it to run.

**Comment by johnco3** [comment]
Thanks for the update, I'm not sure how to tell if the linter plugin is
working, if I run it against my proto file I get nothing out, either it
only complains when things are not valid or its doing nothing?  Also my
antivirus flagged it - but I guess thats because its a new executable.

John

**Comment by ckaznocha** [comment]
An exit code of 0 and no output means it found are no issues with your file. If the linter isn't working protoc should give you some error.

**Comment by johnco3** [comment]
BTW just to try to violate the google protoc style guide, I changed one of
my message names to have a lower case and the linter flagged nothing., I'm
not sure if the executable is doing anything.  It is in my path.  Hopefully
its not a virus :)

i.e.

// individual fault state
message FaultValue {
    oneof oneof_type {
        string name = 1;
        int32 index = 2;
    }
    bool value = 3;}

was changed to

// individual fault state

message faultValue {
    oneof oneof_type {
        string name = 1;
        int32 index = 2;
    }
    bool value = 3;}

**Comment by johnco3** [comment]
Clifton, I tried the test.proto and successfully got 15 errors - I made the
similar violations in my proto file (the one I sent you on friday) however
the linter fails to perform any linting on the proto file.  Try changing
the camel case of any of my messages or enums, you will see no lint
warnings. I'm guessing the imports are confusing the linter.

John

On Sun, Apr 24, 2016 at 10:45 PM, Clifton Kaznocha <notifications@github.com

**Comment by ckaznocha** [comment]
Confirmed your findings, I've just push the fix and will make the release now. Thanks for bearing with me!

**Comment by ckaznocha** [comment]
OK, the new release is here: [v0.1.2](https://github.com/ckaznocha/protoc-gen-lint/releases/tag/v0.1.2)

Everything should work for you, please let me know it it doesn't.

**Comment by johnco3** [comment]
No thank you

All the best and thanks for the linter!

John

On Mon, Apr 25, 2016 at 12:00 AM, Clifton Kaznocha <notifications@github.com

**Comment by johnco3** [comment]
Clifton,

Thanks that works great!  Nice work

John

On Mon, Apr 25, 2016 at 12:10 AM, Clifton Kaznocha <notifications@github.com
