### ISSUE TITLE
Support 'optional' fields in proto3

### ISSUE THREAD

**Issue by huan** [ckaznocha/protoc-gen-lint#20]
Since [protoc@v3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0), it started to support `optional` field. It would be nice if the `protoc-gen-ts` plugin supports it. Could you please work on it? Thanks.

Here is the [reference](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md) about how to implement.

> copy/pasted, credit https://github.com/improbable-eng/ts-protoc-gen/issues/263

This is a blocker for my project https://github.com/wechaty/grpc/issues/109

**Comment by ckaznocha** [comment]
Thanks for letting me know! I'll look into this when I have some time but I can't promise when that will be.

**Comment by ckaznocha** [comment]
Hey @huan I just gave this a try and it looks like optional works fine with proto3. Tested with libprotoc 3.15.8. Do you have any more info on what the issue you're hitting is?

**Comment by huan** [comment]
@ckaznocha Thanks for replying to my issue!

I'll check for it later this month and come back to you, appreciate your great project, it's very helpful to my project. 👍

**Comment by tobias-** [comment]
@ckaznocha Even if @huan hasn't replied yet, could you please make a release so that M1 will work for us?

We're currently blocked from using M1 arch until it's released and would really prefer not to release ourselves.

**Comment by ckaznocha** [comment]
Oh yes, for sure!

**Comment by ckaznocha** [comment]
@tobias- I've changed the way I build releases and don't have an M1 mac to test on but https://github.com/ckaznocha/protoc-gen-lint/releases/download/v0.2.3/protoc-gen-lint_darwin_arm64.zip should work. I'd like to keep the M1 support at #24, If the arm64 doesn't work for you please comment over there and I'll re-open it.

**Comment by huan** [comment]
@ckaznocha I have tried the `protoc-gen-lint@v0.2.4` with `libprotoc@3.18.0` but it does not work in my Ubuntu Linux:

```sh
$ protoc --version
libprotoc 3.18.0
$ go install github.com/ckaznocha/protoc-gen-lint@v0.2.4
$ protoc -I third-party -I proto --lint_out=. $(find proto/ -type f -name *.proto)
wechaty/puppet/friendship.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-lint hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--lint_out: 
```

You can reproducing the above problem with my working PR at https://github.com/wechaty/grpc/pull/125

```sh
$ git clone git@github.com:wechaty/grpc.git
$ cd grpc/
$ git checkout optional
Branch 'optional' set up to track remote branch 'optional' from 'origin'.
Switched to a new branch 'optional'
$ ./scripts/install-protoc.sh 
install skipped: protoc exists
protoc version check: v3.18.0 OK
$ protoc -I third-party -I proto --lint_out=. $(find proto/ -type f -name *.proto)
wechaty/puppet/friendship.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-lint hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--lint_out: 
```
