### ISSUE TITLE
Getting a status code 126 when running linter

### ISSUE THREAD

**Issue by mjstorm94** [ckaznocha/protoc-gen-lint#24]
/usr/local/bin/protoc-gen-lint: /usr/local/bin/protoc-gen-lint: cannot execute binary file
--lint_out: protoc-gen-lint: Plugin failed with status code 126.

I am trying to lint one protobuf file and it gives this error every time. I am using this command:

protoc --lint_out=. FILENAME.proto

**Comment by ckaznocha** [comment]
Hm, thats interesting. Are you using a binary from one of the releases or building from source? Which os/arch are you on?

**Comment by mjstorm94** [comment]
I'm using the latest release, and I'm on Mac OS

**Comment by ckaznocha** [comment]
Do you have an M1 Mac by any chance? The last release doesn't include binaries for it but it will be supported in the next one which could go out at any time. I was just waiting for a response on #20. Alternately you can try building from source which should work fine for an M1.

**Comment by ckaznocha** [comment]
I've changed the way I build releases and don't have an M1 mac to test on but https://github.com/ckaznocha/protoc-gen-lint/releases/download/v0.2.3/protoc-gen-lint_darwin_arm64.zip should work. Gonna close this, please let me know if it doesn't work and I'll re-open
