### ISSUE TITLE
Support message name with a single alphabetic character, like 'X', 'Y', 'X1', 'Y1'

### ISSUE THREAD

**Issue by djeube** [ckaznocha/protoc-gen-lint#25]
Is it possible to support these edge cases when validating message names?

**Comment by ckaznocha** [comment]
Hi @djeube, Is this the same issue addressed by #23?

**Comment by djeube** [comment]
Hi @ckaznocha, indeed, it is fixed in the master branch, my bad!
I used the binary provided for the latest release.
Closing the issue.
