### ISSUE TITLE
linux/arm64 builds are x86_64

### ISSUE THREAD

**Issue by cfstras** [ckaznocha/protoc-gen-lint#28]
I noticed that the latest release for arm64 includes an x86_64 binary instead.

```bash
mkdir protoc-gen-lint_linux_arm64 && cd protoc-gen-lint_linux_arm64
curl -sSLO https://github.com/ckaznocha/protoc-gen-lint/releases/download/v0.2.3/protoc-gen-lint_linux_arm64.zip
unzip protoc-gen-lint_linux_arm64.zip
file protoc-gen-lint
```

Output:
```
protoc-gen-lint_linux_arm64/protoc-gen-lint: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=l37vOoxRha7swXFWPRRu/RTrBCXi-FRWdI_7V03qf/u_DHaiAND98rAROCMkO6/kRU43_m-13vDU_iYkN3Z, not stripped
```

Building the file manually with `GOOS=linux GOARCH=arm64 go build -v .` yields:
```
protoc-gen-lint: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=w6lhE3eaT2E8M26vW0h9/_p18eAbACZ60qZfyfJ8z/XyBF0tnrYva2bnSbqlQd/lQM-vldy2JbQwkDa63Dy, not stripped
```

**Comment by ckaznocha** [comment]
Oops, so sorry about that. Must have been a typo when I switched build systems. I unfortunately won’t be able to fix it for at least a week. It’s probably a very simple fix. If you have time to send a PR I’d be able to merge it promptly 🤪

**Comment by cfstras** [comment]
Just found it, but you were quicker :) Pretty sure https://github.com/ckaznocha/protoc-gen-lint/pull/29 will fix it

**Comment by ckaznocha** [comment]
Ah sorry about that. I just took a peek and spotted it right away. Thanks for letting me know about this!
