### ISSUE TITLE
linter gives missing ";" error when "{}" is the problem

### ISSUE THREAD

**Issue by deltaskelta** [ckaznocha/protoc-gen-lint#8]
When there is a missing `{}` at the end of the rpc definition, the linter gives the error that `;` is missing when that is not really the problem.

```
service Foo {
    rpc SomeFunc(SomeReq) returns (SomeResp) {}
    rpc GetFoo(BarReq) returns (BarResp)
}
```

The `GetFoo` rpc definition will give the missing `;` error

**Comment by ckaznocha** [comment]
Hey @deltaskelta this error comes directly from protoc so there isn't much I can do about it. Its not exactly *wrong*, I believe the `{}` is optional so `rpc GetFoo(BarReq) returns (BarResp);` is valid. Its not a clear message, that's for sure.
