### ISSUE TITLE
Failing import gives no line and column

### ISSUE THREAD

**Issue by deltaskelta** [ckaznocha/protoc-gen-lint#9]
In vim, using https://github.com/w0rp/ale, import errors have no line and column which causes the error to be skipped over. 

I am not very experienced with linters so IDK if this is normal behavior for that sort of error, what do you think? Is it possible to add a line number of where the import happened?

**Comment by ckaznocha** [comment]
Hey @deltaskelta, I wish I could fix this but the error comes directly from protoc so `protoc-gen-lint` can't modify the output. Perhaps ale could be made to match the format with out line/column numbers also?
